# Generated by Django 2.1.5 on 2020-03-23 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='condn',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='books',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='books',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
