# Generated by Django 2.1.5 on 2020-03-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20200323_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='timestamp',
        ),
    ]
