# Generated by Django 2.1.5 on 2020-03-23 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_auto_20200322_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 9, 29, 32, 169370, tzinfo=utc)),
        ),
    ]
