# Generated by Django 2.1.5 on 2020-03-23 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0005_auto_20200323_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 23, 10, 7, 24, 820841, tzinfo=utc)),
        ),
    ]
