# Generated by Django 2.1.5 on 2020-03-25 10:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0008_auto_20200323_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 10, 41, 19, 632378, tzinfo=utc)),
        ),
    ]
